version: '3.8'

services:
  my_app:
    build: .
    container_name: flask_app
    ports:
      - 80:80
    networks:
      - techpronet
    depends_on:
      - database
    restart: always
  database:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: techproed
      MYSQL_PASSWORD: techpro1234
    networks:
      - techpronet
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
networks:
  techpronet:
volumes:
  mysql_data:
    driver: local
  
